### ISSUE TITLE
Production build failed

### ISSUE THREAD

**Issue by f-w** [First-Peoples-Cultural-Council/fv-web-ui#1]
I get following build error on both linux and windows.

```
+ gulp build:production
[06:39:07] Using gulpfile ~/jobs/fv-web-ui/workspace/gulpfile.js
[06:39:07] Starting 'build:production'...
[06:39:07] Starting 'clean'...
[06:39:07] Finished 'clean' after 16 ms
[06:39:07] Starting 'fonts'...
[06:39:07] Starting 'images'...
[06:39:07] Finished 'fonts' after 39 ms
[06:39:07] gulp-imagemin: Minified 0 images (saved 0 B - 0%)
[06:39:07] Finished 'images' after 28 ms
[06:39:07] Starting 'webpack:production'...
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/var/jenkins_home/jobs/fv-web-ui/workspace/public/rev-manifest.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at Compiler.<anonymous> (/var/jenkins_home/jobs/fv-web-ui/workspace/gulpfile.js/lib/webpackManifest.js:16:10)
    at Compiler.applyPlugins (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/tapable/lib/Tapable.js:26:37)
    at Compiler.<anonymous> (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/webpack/lib/Compiler.js:180:11)
    at /var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/var/jenkins_home/jobs/fv-web-ui/workspace/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:137:4)
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

What node version do you use in dev? I have tried 0.10, 4, 5. All failed.

**Comment by dy2288** [comment]
Strange - I just tried locally on a clean machine and managed to build following the instructions (on Ubuntu, had no problems on Windows either).

If you run only `gulp webpack:production`, do you see a *rev-manifest.json* being generated in the public folder?
